config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :expenditures

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :expenditures, foreign_key: 'category_id', dependent: :destroy

  validates :name, presence: true
  validates :name, length: { maximum: 25 }
  validates :icon, presence: true
end

app/models/expenditure.rb
class Expenditure < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  belongs_to :category, foreign_key: 'category_id'

  validates :name, presence: true
  validates :name, length: { maximum: 25 }
  validates :amount, presence: true
  validates :amount, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, foreign_key: 'user_id', dependent: :destroy
  has_many :expenditures, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[email password])
  end

  private

  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all.where(user: current_user)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @expenditures = Expenditure.all.where(category_id: params[:id]).order('created_at DESC')
    @total_amount = 0

    @expenditures.each do |spend|
      @total_amount += spend.amount
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :set_expenditure, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /expenditures or /expenditures.json
  def index
    @expenditures = Expenditure.all.where(user: current_user).order('created_at DESC')
  end

  # GET /expenditures/1 or /expenditures/1.json
  def show; end

  # GET /expenditures/new
  def new
    @expenditure = Expenditure.new
    @categories = Category.all.where(user: current_user)
  end

  # GET /expenditures/1/edit
  def edit; end

  # POST /expenditures or /expenditures.json
  def create
    @expenditure = Expenditure.new(expenditure_params)
    @expenditure.author_id = current_user.id

    respond_to do |format|
      if @expenditure.save
        format.html { redirect_to @expenditure, notice: 'Expenditure was successfully created.' }
        format.json { render :show, status: :created, location: @expenditure }
      else
        format.html { redirect_to expenditures_path, notice: 'Select a category to create a new expense' }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenditures/1 or /expenditures/1.json
  def update
    respond_to do |format|
      if @expenditure.update(expenditure_params)
        format.html { redirect_to expenditure_url(@expenditure), notice: 'Expenditure was successfully updated.' }
        format.json { render :show, status: :ok, location: @expenditure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expenditure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenditures/1 or /expenditures/1.json
  def destroy
    @expenditure.destroy

    respond_to do |format|
      format.html { redirect_to expenditures_url, notice: 'Expenditure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expenditure
    @expenditure = Expenditure.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expenditure_params
    params.require(:expenditure).permit(:name, :amount, :category_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = 'Exp. Manager'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div class='cat-card-cont border rounded' id="<%= dom_id category %>">

    <div class='card-data-cont d-flex justify-content-between'>

      <div class='img-cont'>
        <%= image_tag("icons/#{category.icon}.png")%>
      </div>
      <div class='cat-name'>
        <%= link_to category.name, category_path(category.id)%>
      </div>
      <div>
        <%= button_to 'Remove', category_path(category.id), method: :delete, class: 'btn btn-outline-danger' %>
      </div>

    </div>
</div>

app/views/categories/_form.html.erb
<%
  categories = [
    {
      icon: 'bill_icon',
      name: 'Bills'
    },
    {
      icon: 'food_icon',
      name: 'Food'
    },
    {
      icon: 'game_icon',
      name: 'Videogames'
    },
    {
      icon: 'healthcare_icon',
      name: 'Healthcare'
    },
    {
      icon: 'movies_icon',
      name: 'Entertaiment'
    },
    {
      icon: 'music_icon',
      name: 'Music'
    },
    {
      icon: 'sports_icon',
      name: 'Sports'
    }
  ]
%>

<%= form_with(model: category, class: 'form-cat-cont') do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :icon, required: 'required' %>

  <div class='form-name-cont'>
    <%= form.text_field :name, class: 'input-cat', placeholder: 'Category name' %>
  </div>

  <div class='cat-icon'>
    <%= form.label :Select_Icon, class: 'icon-label' %>
    <div class='icon-container'>
      <% categories.each do |cat| %>
        <div id="card_<%= cat[:icon]%>" class='icon-card border rounded' onclick = "iconChoice('<%= cat[:icon]%>')">
          <img src="<%=asset_path("icons/#{cat[:icon]}.png")%>" alt="<%=cat[:name] %>" class="card-image">
          <%= cat[:name] %>
        </div>
      <% end %>
    </div>
  </div>

  <div class='sub-cat-cont'>
    <%= form.submit class: 'btn btn-outline-success sub-btn' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class='new-sess'>
  <header class='container d-flex justify-content-between align-items-center index-cat'>
    <%= render 'shared/dropdown_menu' %>
    <h1 class='mb-0 title'>CATEGORIES</h1>
    <i class="fa-solid fa-magnifying-glass"></i>
  </header>

  <main class='container'>

    <p style="color: green"><%= notice %></p>
    <% if @categories.empty? %>
      <p class='no-cat'>No categories to show</p>
    <% else %>
      <div id="categories">
        <% @categories.each do |category| %>
          <%= render category %>
        <% end %>
      </div>
    <% end %>
    <div class='sub-cat-cont'>
      <%= link_to "New category", new_category_path, class: 'btn btn-green sub-btn' %>
    </div>
  </main>
</div>

app/views/categories/new.html.erb
<div class='new-sess'>
  <header class='container d-flex justify-content-between align-items-center index-cat'>
    <%= render 'shared/dropdown_menu' %>
    <h1 class='mb-0 title'>NEW CATEGORY</h1>
    <i class="fa-solid fa-magnifying-glass"></i>
  </header>

  <main class='container pb-5'>
    <%= render "form", category: @category %>
    <div class='back-cat-btn '>
      <%= link_to "Back to categories", categories_path, class:'btn btn-outline-secondary back-btn' %>
    </div>
  </main>
</div>
<script>
const icon_input = document.getElementById('category_icon');
const icon_cards = document.querySelectorAll('.icon-card');

const cleanClass = (card_arr) => {
  for(let i = 0; i < card_arr.length; i += 1) {
    card_arr[i].classList.remove('selected')
  };
}

const iconChoice = (icon) => {
  cleanClass(icon_cards);
  icon_input.value = icon;
  document.getElementById(`card_${icon}`).classList.add('selected')
}
</script>

app/views/categories/show.html.erb
<div class='new-sess'>
  <header class='container d-flex justify-content-between align-items-center index-cat'>
    <%= render 'shared/dropdown_menu' %>
    <h1 class='mb-0 title'>CATEGORY</h1>
    <i class="fa-solid fa-magnifying-glass"></i>
  </header>

  <main class='container pb-5'>
    <p style="color: green"><%= notice %></p>

    <%= render @category %>

    <div class='total-exp d-flex justify-content-between rounded'>
      <h2 class='exp-title'>Total spend:</h2>
      <h2>$<%= @total_amount %></h2>
    </div>

    <div class='exp-container'>
      <% @expenditures.each do |spend|%>
        <%= link_to expenditure_path(spend) do%>
          <div class='exp-card-cont d-flex justify-content-between p-3 border rounded'>
            <h2 class='exp-title'><%= spend.name %></h2>
            <h2>$<%= spend.amount %></h2>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class='sub-cat-cont mb-4'>
      <%= link_to 'New expense', new_expenditure_path, class: 'btn btn-green sub-btn'%>
    </div>

    <div class='back-cat-btn '>
      <%= link_to "Back to categories", categories_path, class:'btn btn-outline-secondary back-btn' %>
    </div>
  </main>
</div>

app/views/expenditures/_expenditure.html.erb
<div id="<%= dom_id expenditure %>">

  <div class='exp-card-container d-flex justify-content-between border rounded mb-3 p-3'>
          <%Category.where(id: expenditure.category_id).each do |cat| %>
            <img src="<%=asset_path("icons/#{cat.icon}.png")%>" alt="<%=cat.name %>" class="card-image">
          <%end%>

              <p class='info-title exp-info'>
                <%= expenditure.name %>
              </p>

              <p class='info-amount exp-info'>$
                <%= expenditure.amount %>
              </p>
        </div>


</div>

app/views/expenditures/_form.html.erb
<%= form_with(model: expenditure) do |form| %>
  <% if expenditure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expenditure.errors.count, "error") %> prohibited this expenditure from being saved:</h2>

      <ul>
        <% expenditure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :category_id, required: 'required' %>

  <div class='form-cont'>
    <%= form.label :Select_category, class: 'exp-label' %>
    <div class='exp-cat-cont d-flex'>
      <% @categories.each do |cat| %>
        <div class='exp-cat-card border p-3' id="<%= cat.id%>" onclick = "iconChoice('<%= cat.id%>')">
          <img src="<%=asset_path("icons/#{cat.icon}.png")%>" alt="<%=cat.name %>" class="card-image">
          <p><%= cat.name%></p>
        </div>
      <%end%>
    </div>
  </div>

  <div class='form-cont'>
    <%= form.text_field :name, placeholder: 'Name', class: 'form-input' %>
  </div>

  <div class='form-cont'>
    <%= form.number_field :amount, placeholder: 'Amount', class: 'form-input' %>
  </div>

  <div class= 'sub-cat-cont mb-4'>
    <%= form.submit class: 'btn btn-outline-success sub-btn' %>
  </div>
<% end %>

<script>
const icon_input = document.getElementById('expenditure_category_id');
const icon_cards = document.querySelectorAll('.exp-cat-card');

const cleanClass = (card_arr) => {
  for(let i = 0; i < card_arr.length; i += 1) {
    card_arr[i].classList.remove('cat-selected')
  };
}

const iconChoice = (icon) => {
  cleanClass(icon_cards);
  icon_input.value = icon;
  document.getElementById(`${icon}`).classList.add('cat-selected')
}
</script>

app/views/expenditures/edit.html.erb
<h1>Editing expenditure</h1>

<%= render "form", expenditure: @expenditure %>

<br>

<div>
  <%= link_to "Show this expenditure", @expenditure %> |
  <%= link_to "Back to expenditures", expenditures_path %>
</div>

app/views/expenditures/index.html.erb
<div class='new-sess'>
  <header class='container d-flex justify-content-between align-items-center index-cat'>
    <%= render 'shared/dropdown_menu' %>
    <h1 class='mb-0 title'>EXPENDITURES</h1>
    <i class="fa-solid fa-magnifying-glass"></i>
  </header>

  <main class='container'>

    <p style="color: green"><%= notice %></p>

    <% if @expenditures.empty?%>
      <p class='no-cat'>No expenditures to show</p>
    <% else %>
      <div id="expenditures">
        <% @expenditures.each do |expenditure| %>
          <%= link_to expenditure_path(expenditure) do %>
            <%= render expenditure %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <div class='sub-cat-cont'>
      <%= link_to "New expenditure", new_expenditure_path, class: 'btn btn-green sub-btn' %>
    </div>
  </main>
</div>

app/views/expenditures/new.html.erb
<div class='new-sess'>
  <header class='container d-flex justify-content-between align-items-center index-cat'>
    <%= render 'shared/dropdown_menu' %>
    <h1 class='mb-0 title'>EXPENDITURES</h1>
    <i class="fa-solid fa-magnifying-glass"></i>
  </header>

  <main class='container'>

    <p style="color: green"><%= notice %></p>

    <%= render "form", expenditure: @expenditure %>

    <div class='sub-cat-cont'>
      <%= link_to "Back to expenditures", expenditures_path, class: 'btn btn-outline-secondary btn-exp' %>
    </div>
  </main>
</div>

app/views/expenditures/show.html.erb
<div class='new-sess'>
  <header class='container d-flex justify-content-between align-items-center index-cat'>
    <%= render 'shared/dropdown_menu' %>
    <h1 class='mb-0 title'>EXPENDITURES</h1>
    <i class="fa-solid fa-magnifying-glass"></i>
  </header>

  <main class='container'>

    <p style="color: green"><%= notice %></p>

    <%= render @expenditure %>

    <div class='sub-cat-cont mb-4'>
      <%= button_to "Destroy this expenditure", @expenditure, method: :delete, class: 'btn btn-danger sub-btn' %>
    </div>

    <div class='back-cat-btn '>
      <%= link_to "Back to expenditures", expenditures_path, class:'btn btn-outline-secondary back-btn' %>
    </div>
  </main>
</div>

app/views/home/index.html.erb
 <% if user_signed_in?%>
 <header class='container d-flex justify-content-between align-items-center index-cat'>
    <%= render 'shared/dropdown_menu' %>
    <h1 class='mb-0 title'>HOME</h1>
    <i class="fa-solid fa-magnifying-glass"></i>
  </header>
<% end %>
<p style="color: green"><%= notice %></p>
<main class='container home-main d-flex'>
  <img src="<%=asset_path("logo/logo-color.png")%>" alt="Logo">
</main>
<% unless user_signed_in?%>
  <%= render 'shared/splash_nav' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpensesManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_dropdown_menu.html.erb
<nav class='navbar navbar-dark navbar-expand-lg ul-nav'>

  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">

    <span class='navbar-toggler-icon'></span>

  </button>

  <div class='collapse navbar-collapse' id='navbarTogglerDemo01'>
    <ul class='navbar-nav mr-auto'>
      <li class='nav-item'>
        <%= link_to 'Categories', categories_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'Expenses', expenditures_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'log-out-btn nav-link' %>
      </li>
    </ul>
  </div>

</nav>

app/views/shared/_splash_nav.html.erb
<nav class='container home-nav'>
  <ul class='d-flex'>
       <% if user_signed_in? %>
        <li>
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
        </li>
        <li>
          <%= link_to 'Categories', categories_path %>
        </li>
        <li>
          <%= current_user.name %>
        </li>
      <% else %>
        <%= link_to new_user_session_path do %>
        <li class='log rounded'>
           LOG IN
        </li>
        <% end %>

        <%= link_to new_user_registration_path do %>
        <li>
            SIGN UP
        </li>
        <% end %>
      <% end %>
  </ul>
</nav>